version: "3.8"

services:
  database:
    image: postgres:15
    container_name: directus-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    container_name: directus-app
    restart: always
    ports:
      - "8055:8055"
    environment:
      DB_CLIENT: "pg"
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      KEY: ${KEY}
      SECRET: ${SECRET}

      PUBLIC_URL: ${PUBLIC_URL}
      TRUST_PROXY: "true"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - database

volumes:
  db_data:


